create table if not exists users (
  id text primary key,
  name text not null,
  gender text,
  age integer,
  height numeric,
  weight numeric,
  goal text,
  experience text,
  environment text,
  equipment jsonb default '[]'::jsonb,
  diet_preference text,
  diet_restrictions text,
  activity_level text
);

create table if not exists workout_plans (
  id bigint generated by default as identity primary key,
  user_id text references users(id) on delete cascade,
  plan_json jsonb not null,
  environment text,
  equipment jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists training_history (
  id bigint generated by default as identity primary key,
  user_id text references users(id) on delete cascade,
  date date not null,
  completion_rate numeric,
  fatigue_level integer,
  feedback jsonb,
  weight numeric,
  unique(user_id, date)
);

-- If the original three tables already exist, run these additive migrations:
alter table users add column if not exists diet_preference text;
alter table users add column if not exists diet_restrictions text;
alter table users add column if not exists activity_level text;
